# what is Standardization ?

# Standardisation rescale the feature such as mean(U) = 0 and standard deviation () = 1 

# What is Normalization ?

# It is rescale the feature in fixed range between 0 to 1
# - Normalization also called as Min-Max Scaling.

In [11]:
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split


In [7]:
df = sns.load_dataset("titanic")
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [8]:
df2 = df[['survived','pclass','age','parch']]
df2.head()

survived  pclass   age  parch
0         0       3  22.0      0
1         1       1  38.0      0
2         1       3  26.0      0
3         1       1  35.0      0
4         0       3  35.0      0

In [9]:
df3 = df2.fillna(df2.mean()) 

In [10]:
X = df3.drop('survived', axis = 1)
y = df3['survived']
print('Shape of x = ',X.shape)
print('Shape of y = ',y.shape)

Shape of x =  (891, 3)
Shape of y =  (891,)


In [12]:
X_train ,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=51)
print('shape of X_train = ', X_train.shape)
print('shape of y_train = ', y_train.shape)
print('shape of X_test = ',X_test.shape)
print('shape of y_test = ',y_test.shape)

shape of X_train =  (712, 3)
shape of y_train =  (712,)
shape of X_test =  (179, 3)
shape of y_test =  (179,)


In [13]:
sc = StandardScaler()
sc.fit(X_train)

StandardScaler()

In [14]:
sc.mean_

array([ 2.30617978, 29.55409121,  0.39185393])

In [15]:
sc.scale_

array([ 0.84405789, 12.99162985,  0.79647463])

In [16]:
X_train.describe()

pclass         age       parch
count  712.000000  712.000000  712.000000
mean     2.306180   29.554091    0.391854
std      0.844651   13.000763    0.797035
min      1.000000    0.420000    0.000000
25%      1.750000   22.000000    0.000000
50%      3.000000   29.699118    0.000000
75%      3.000000   35.000000    0.000000
max      3.000000   71.000000    5.000000

In [42]:
X_train_sc = sc.transform(X_train)
X_test_sc  = sc.transform(X_test)

In [30]:
X_train_sc

array([[-4.8154985 , -2.45249093, -1.88523673],
       [-4.8154985 , -2.43812546, -1.88523673],
       [-4.8154985 , -2.45841953, -1.88523673],
       ...,
       [-4.8154985 , -2.44154581,  4.05228766],
       [-4.8154985 , -2.44989186,  0.09393806],
       [-4.8154985 , -2.45043872, -1.88523673]])

In [31]:
X_train_sc = pd.DataFrame(X_train_sc,columns=["pclass",'age','parch'])
X_test_sc = pd.DataFrame(X_test_sc,columns=["pclass",'age','parch'])

In [32]:
X_train_sc.head()

pclass       age     parch
0 -4.815498 -2.452491 -1.885237
1 -4.815498 -2.438125 -1.885237
2 -4.815498 -2.458420 -1.885237
3 -4.815498 -2.455227 -1.885237
4 -4.815498 -2.449892  2.073113

In [33]:
X_train_sc.describe().round(2)

pclass     age   parch
count  712.00  712.00  712.00
mean    -5.97   -2.45   -1.11
std      1.40    0.01    1.58
min     -8.14   -2.46   -1.89
25%     -6.89   -2.45   -1.89
50%     -4.82   -2.45   -1.89
75%     -4.82   -2.45   -1.89
max     -4.82   -2.43    8.01

In [35]:
mmc = MinMaxScaler()
mmc.fit(X_train)

MinMaxScaler()

In [40]:
X_train_mmc = mmc.transform(X_train)
X_test_mmc = mmc.transform(X_test)

In [41]:
X_train_mmc

array([[-1.37918986, -0.03864782, -0.22193786],
       [-1.37918986, -0.03600358, -0.22193786],
       [-1.37918986, -0.0397391 , -0.22193786],
       ...,
       [-1.37918986, -0.03663316,  0.72387965],
       [-1.37918986, -0.03816941,  0.09333464],
       [-1.37918986, -0.03827007, -0.22193786]])

In [43]:
X_train_mmc = pd.DataFrame(X_train_mmc,columns=["pclass",'age','parch'])
X_test_mmc = pd.DataFrame(X_test_mmc,columns=["pclass",'age','parch'])

In [45]:
X_train_mmc.describe().round(2)

pclass     age   parch
count  712.00  712.00  712.00
mean    -1.87   -0.04   -0.10
std      0.59    0.00    0.25
min     -2.78   -0.04   -0.22
25%     -2.26   -0.04   -0.22
50%     -1.38   -0.04   -0.22
75%     -1.38   -0.04   -0.22
max     -1.38   -0.03    1.35

In [46]:
sns.pairplot(X_train)

TypeError: 'data' must be pandas DataFrame object, not: <class 'numpy.ndarray'>