# Random Sampling with NumPy

In [1]:
import numpy as np
import random

In [2]:
np.random.random(1)

array([0.08728139])

In [3]:
np.random.random((3,3))

array([[0.93556597, 0.16573062, 0.70083112],
       [0.53822086, 0.91382866, 0.9755117 ],
       [0.74071989, 0.67134516, 0.59405662]])

In [4]:
np.random.randint(1,4)

1

In [6]:
np.random.randint(1,4,(4,4))

array([[3, 3, 2, 1],
       [3, 1, 3, 1],
       [2, 3, 1, 1],
       [1, 1, 3, 2]])

In [9]:
np.random.randint(1,4, (2,4,4))

array([[[2, 2, 3, 3],
        [1, 3, 2, 2],
        [1, 2, 2, 3],
        [2, 3, 1, 1]],

       [[2, 3, 3, 3],
        [3, 1, 2, 3],
        [3, 3, 2, 1],
        [3, 1, 3, 3]]])

In [10]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [11]:
np.random.rand(3)   

array([0.13145815, 0.41366737, 0.77872881])

In [12]:
np.random.randn(3)  # both negative and positive

array([-1.25424191,  0.33157855, -0.30860049])

In [13]:
x= [1,2,3,4]      
np.random.choice(x)

2

In [14]:
for i in range(20):
    print(np.random.choice(x))

2
3
4
3
1
4
1
3
1
2
4
3
1
3
4
1
4
2
3
4


In [15]:
x

[1, 2, 3, 4]

In [16]:
np.random.permutation(x)

array([3, 2, 1, 4])