In [12]:
import numpy as np

In [13]:
arr_1d =np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [14]:
type(arr_1d)

numpy.ndarray

In [15]:
arr_1d.ndim

1

In [16]:
arr_2d =np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [17]:
type(arr_2d)

numpy.ndarray

In [18]:
arr_2d.ndim

2

In [19]:
arr_2d.size

8

In [20]:
arr_2d.shape

(2, 4)

In [21]:
arr_2d.dtype

dtype('int32')

In [23]:
mx_1s= np.ones(5)
print(mx_1s)

[1. 1. 1. 1. 1.]


In [24]:
mx_1s.dtype

dtype('float64')

In [25]:
mx_1s =np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [26]:
mx_1s =np.ones((3,4),dtype=int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [27]:
mx_0s =np.zeros((4,6))
print(mx_0s)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [28]:
mx_0s = np.zeros((4,6),dtype= bool)
print(mx_0s)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [29]:
mx_0s =np.zeros((2,4),dtype = str)
print(mx_0s)

[['' '' '' '']
 ['' '' '' '']]


In [30]:
em_srt = ''
print(bool(em_srt))

False


In [31]:
em_mx =np.empty((3,3))
print(em_mx)

[[ 2.23429209e+248 -8.69256922e-311  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000]]
